// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package customizations

import (
	v20210601 "github.com/Azure/azure-service-operator/v2/api/network.frontdoor/v1api20210601"
	v20210601s "github.com/Azure/azure-service-operator/v2/api/network.frontdoor/v1api20210601/storage"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
)

type FrontDoorExtension struct {
}

// GetExtendedResources Returns the KubernetesResource slice for Resource versions
func (extension *FrontDoorExtension) GetExtendedResources() []genruntime.KubernetesResource {
	return []genruntime.KubernetesResource{
		&v20210601.FrontDoor{},
		&v20210601s.FrontDoor{}}
}
