// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101

import "github.com/Azure/azure-service-operator/v2/pkg/genruntime"

type ManagedInstances_ServerTrustCertificate_Spec_ARM struct {
	Name string `json:"name,omitempty"`

	// Properties: Resource properties.
	Properties *ServerTrustCertificateProperties_ARM `json:"properties,omitempty"`
}

var _ genruntime.ARMResourceSpec = &ManagedInstances_ServerTrustCertificate_Spec_ARM{}

// GetAPIVersion returns the ARM API version of the resource. This is always "2021-11-01"
func (certificate ManagedInstances_ServerTrustCertificate_Spec_ARM) GetAPIVersion() string {
	return string(APIVersion_Value)
}

// GetName returns the Name of the resource
func (certificate *ManagedInstances_ServerTrustCertificate_Spec_ARM) GetName() string {
	return certificate.Name
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Sql/managedInstances/serverTrustCertificates"
func (certificate *ManagedInstances_ServerTrustCertificate_Spec_ARM) GetType() string {
	return "Microsoft.Sql/managedInstances/serverTrustCertificates"
}

// The properties of a server trust certificate.
type ServerTrustCertificateProperties_ARM struct {
	// PublicBlob: The certificate public blob
	PublicBlob *string `json:"publicBlob,omitempty"`
}
