// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101

type ManagedInstances_ServerTrustCertificate_STATUS_ARM struct {
	// Id: Resource ID.
	Id *string `json:"id,omitempty"`

	// Name: Resource name.
	Name *string `json:"name,omitempty"`

	// Properties: Resource properties.
	Properties *ServerTrustCertificateProperties_STATUS_ARM `json:"properties,omitempty"`

	// Type: Resource type.
	Type *string `json:"type,omitempty"`
}

// The properties of a server trust certificate.
type ServerTrustCertificateProperties_STATUS_ARM struct {
	// CertificateName: The certificate name
	CertificateName *string `json:"certificateName,omitempty"`

	// PublicBlob: The certificate public blob
	PublicBlob *string `json:"publicBlob,omitempty"`

	// Thumbprint: The certificate thumbprint
	Thumbprint *string `json:"thumbprint,omitempty"`
}
