// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101

import "github.com/Azure/azure-service-operator/v2/pkg/genruntime"

type ManagedInstances_DistributedAvailabilityGroup_Spec_ARM struct {
	Name string `json:"name,omitempty"`

	// Properties: Resource properties.
	Properties *DistributedAvailabilityGroupProperties_ARM `json:"properties,omitempty"`
}

var _ genruntime.ARMResourceSpec = &ManagedInstances_DistributedAvailabilityGroup_Spec_ARM{}

// GetAPIVersion returns the ARM API version of the resource. This is always "2021-11-01"
func (group ManagedInstances_DistributedAvailabilityGroup_Spec_ARM) GetAPIVersion() string {
	return string(APIVersion_Value)
}

// GetName returns the Name of the resource
func (group *ManagedInstances_DistributedAvailabilityGroup_Spec_ARM) GetName() string {
	return group.Name
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Sql/managedInstances/distributedAvailabilityGroups"
func (group *ManagedInstances_DistributedAvailabilityGroup_Spec_ARM) GetType() string {
	return "Microsoft.Sql/managedInstances/distributedAvailabilityGroups"
}

// The properties of a distributed availability group.
type DistributedAvailabilityGroupProperties_ARM struct {
	// PrimaryAvailabilityGroupName: The primary availability group name
	PrimaryAvailabilityGroupName *string `json:"primaryAvailabilityGroupName,omitempty"`

	// ReplicationMode: The replication mode of a distributed availability group. Parameter will be ignored during link
	// creation.
	ReplicationMode *DistributedAvailabilityGroupProperties_ReplicationMode `json:"replicationMode,omitempty"`

	// SecondaryAvailabilityGroupName: The secondary availability group name
	SecondaryAvailabilityGroupName *string `json:"secondaryAvailabilityGroupName,omitempty"`

	// SourceEndpoint: The source endpoint
	SourceEndpoint *string `json:"sourceEndpoint,omitempty"`

	// TargetDatabase: The name of the target database
	TargetDatabase *string `json:"targetDatabase,omitempty"`
}
