// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_ManagedInstances_DistributedAvailabilityGroup_STATUS_ARM_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of ManagedInstances_DistributedAvailabilityGroup_STATUS_ARM via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForManagedInstances_DistributedAvailabilityGroup_STATUS_ARM, ManagedInstances_DistributedAvailabilityGroup_STATUS_ARMGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForManagedInstances_DistributedAvailabilityGroup_STATUS_ARM runs a test to see if a specific instance of ManagedInstances_DistributedAvailabilityGroup_STATUS_ARM round trips to JSON and back losslessly
func RunJSONSerializationTestForManagedInstances_DistributedAvailabilityGroup_STATUS_ARM(subject ManagedInstances_DistributedAvailabilityGroup_STATUS_ARM) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual ManagedInstances_DistributedAvailabilityGroup_STATUS_ARM
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of ManagedInstances_DistributedAvailabilityGroup_STATUS_ARM instances for property testing - lazily
// instantiated by ManagedInstances_DistributedAvailabilityGroup_STATUS_ARMGenerator()
var managedInstances_DistributedAvailabilityGroup_STATUS_ARMGenerator gopter.Gen

// ManagedInstances_DistributedAvailabilityGroup_STATUS_ARMGenerator returns a generator of ManagedInstances_DistributedAvailabilityGroup_STATUS_ARM instances for property testing.
// We first initialize managedInstances_DistributedAvailabilityGroup_STATUS_ARMGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func ManagedInstances_DistributedAvailabilityGroup_STATUS_ARMGenerator() gopter.Gen {
	if managedInstances_DistributedAvailabilityGroup_STATUS_ARMGenerator != nil {
		return managedInstances_DistributedAvailabilityGroup_STATUS_ARMGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup_STATUS_ARM(generators)
	managedInstances_DistributedAvailabilityGroup_STATUS_ARMGenerator = gen.Struct(reflect.TypeOf(ManagedInstances_DistributedAvailabilityGroup_STATUS_ARM{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup_STATUS_ARM(generators)
	AddRelatedPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup_STATUS_ARM(generators)
	managedInstances_DistributedAvailabilityGroup_STATUS_ARMGenerator = gen.Struct(reflect.TypeOf(ManagedInstances_DistributedAvailabilityGroup_STATUS_ARM{}), generators)

	return managedInstances_DistributedAvailabilityGroup_STATUS_ARMGenerator
}

// AddIndependentPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup_STATUS_ARM is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup_STATUS_ARM(gens map[string]gopter.Gen) {
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup_STATUS_ARM is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup_STATUS_ARM(gens map[string]gopter.Gen) {
	gens["Properties"] = gen.PtrOf(DistributedAvailabilityGroupProperties_STATUS_ARMGenerator())
}

func Test_DistributedAvailabilityGroupProperties_STATUS_ARM_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of DistributedAvailabilityGroupProperties_STATUS_ARM via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForDistributedAvailabilityGroupProperties_STATUS_ARM, DistributedAvailabilityGroupProperties_STATUS_ARMGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForDistributedAvailabilityGroupProperties_STATUS_ARM runs a test to see if a specific instance of DistributedAvailabilityGroupProperties_STATUS_ARM round trips to JSON and back losslessly
func RunJSONSerializationTestForDistributedAvailabilityGroupProperties_STATUS_ARM(subject DistributedAvailabilityGroupProperties_STATUS_ARM) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual DistributedAvailabilityGroupProperties_STATUS_ARM
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of DistributedAvailabilityGroupProperties_STATUS_ARM instances for property testing - lazily instantiated
// by DistributedAvailabilityGroupProperties_STATUS_ARMGenerator()
var distributedAvailabilityGroupProperties_STATUS_ARMGenerator gopter.Gen

// DistributedAvailabilityGroupProperties_STATUS_ARMGenerator returns a generator of DistributedAvailabilityGroupProperties_STATUS_ARM instances for property testing.
func DistributedAvailabilityGroupProperties_STATUS_ARMGenerator() gopter.Gen {
	if distributedAvailabilityGroupProperties_STATUS_ARMGenerator != nil {
		return distributedAvailabilityGroupProperties_STATUS_ARMGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForDistributedAvailabilityGroupProperties_STATUS_ARM(generators)
	distributedAvailabilityGroupProperties_STATUS_ARMGenerator = gen.Struct(reflect.TypeOf(DistributedAvailabilityGroupProperties_STATUS_ARM{}), generators)

	return distributedAvailabilityGroupProperties_STATUS_ARMGenerator
}

// AddIndependentPropertyGeneratorsForDistributedAvailabilityGroupProperties_STATUS_ARM is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForDistributedAvailabilityGroupProperties_STATUS_ARM(gens map[string]gopter.Gen) {
	gens["DistributedAvailabilityGroupId"] = gen.PtrOf(gen.AlphaString())
	gens["LastHardenedLsn"] = gen.PtrOf(gen.AlphaString())
	gens["LinkState"] = gen.PtrOf(gen.AlphaString())
	gens["PrimaryAvailabilityGroupName"] = gen.PtrOf(gen.AlphaString())
	gens["ReplicationMode"] = gen.PtrOf(gen.OneConstOf(DistributedAvailabilityGroupProperties_ReplicationMode_STATUS_Async, DistributedAvailabilityGroupProperties_ReplicationMode_STATUS_Sync))
	gens["SecondaryAvailabilityGroupName"] = gen.PtrOf(gen.AlphaString())
	gens["SourceEndpoint"] = gen.PtrOf(gen.AlphaString())
	gens["SourceReplicaId"] = gen.PtrOf(gen.AlphaString())
	gens["TargetDatabase"] = gen.PtrOf(gen.AlphaString())
	gens["TargetReplicaId"] = gen.PtrOf(gen.AlphaString())
}
