// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101

import "github.com/Azure/azure-service-operator/v2/pkg/genruntime"

type Servers_Databases_WorkloadGroup_Spec_ARM struct {
	Name string `json:"name,omitempty"`

	// Properties: Resource properties.
	Properties *WorkloadGroupProperties_ARM `json:"properties,omitempty"`
}

var _ genruntime.ARMResourceSpec = &Servers_Databases_WorkloadGroup_Spec_ARM{}

// GetAPIVersion returns the ARM API version of the resource. This is always "2021-11-01"
func (group Servers_Databases_WorkloadGroup_Spec_ARM) GetAPIVersion() string {
	return string(APIVersion_Value)
}

// GetName returns the Name of the resource
func (group *Servers_Databases_WorkloadGroup_Spec_ARM) GetName() string {
	return group.Name
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Sql/servers/databases/workloadGroups"
func (group *Servers_Databases_WorkloadGroup_Spec_ARM) GetType() string {
	return "Microsoft.Sql/servers/databases/workloadGroups"
}

// Workload group definition. For more information look at sys.workload_management_workload_groups (DMV).
type WorkloadGroupProperties_ARM struct {
	// Importance: The workload group importance level.
	Importance *string `json:"importance,omitempty"`

	// MaxResourcePercent: The workload group cap percentage resource.
	MaxResourcePercent *int `json:"maxResourcePercent,omitempty"`

	// MaxResourcePercentPerRequest: The workload group request maximum grant percentage.
	MaxResourcePercentPerRequest *float64 `json:"maxResourcePercentPerRequest,omitempty"`

	// MinResourcePercent: The workload group minimum percentage resource.
	MinResourcePercent *int `json:"minResourcePercent,omitempty"`

	// MinResourcePercentPerRequest: The workload group request minimum grant percentage.
	MinResourcePercentPerRequest *float64 `json:"minResourcePercentPerRequest,omitempty"`

	// QueryExecutionTimeout: The workload group query execution timeout.
	QueryExecutionTimeout *int `json:"queryExecutionTimeout,omitempty"`
}
