// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101

import (
	"encoding/json"
	v20211101s "github.com/Azure/azure-service-operator/v2/api/sql/v1beta20211101storage"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_Servers_Databases_SyncGroups_SyncMember_WhenConvertedToHub_RoundTripsWithoutLoss(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	parameters.MinSuccessfulTests = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip from Servers_Databases_SyncGroups_SyncMember to hub returns original",
		prop.ForAll(RunResourceConversionTestForServers_Databases_SyncGroups_SyncMember, Servers_Databases_SyncGroups_SyncMemberGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(false, 240, os.Stdout))
}

// RunResourceConversionTestForServers_Databases_SyncGroups_SyncMember tests if a specific instance of Servers_Databases_SyncGroups_SyncMember round trips to the hub storage version and back losslessly
func RunResourceConversionTestForServers_Databases_SyncGroups_SyncMember(subject Servers_Databases_SyncGroups_SyncMember) string {
	// Copy subject to make sure conversion doesn't modify it
	copied := subject.DeepCopy()

	// Convert to our hub version
	var hub v20211101s.Servers_Databases_SyncGroups_SyncMember
	err := copied.ConvertTo(&hub)
	if err != nil {
		return err.Error()
	}

	// Convert from our hub version
	var actual Servers_Databases_SyncGroups_SyncMember
	err = actual.ConvertFrom(&hub)
	if err != nil {
		return err.Error()
	}

	// Compare actual with what we started with
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

func Test_Servers_Databases_SyncGroups_SyncMember_WhenPropertiesConverted_RoundTripsWithoutLoss(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip from Servers_Databases_SyncGroups_SyncMember to Servers_Databases_SyncGroups_SyncMember via AssignProperties_To_Servers_Databases_SyncGroups_SyncMember & AssignProperties_From_Servers_Databases_SyncGroups_SyncMember returns original",
		prop.ForAll(RunPropertyAssignmentTestForServers_Databases_SyncGroups_SyncMember, Servers_Databases_SyncGroups_SyncMemberGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(false, 240, os.Stdout))
}

// RunPropertyAssignmentTestForServers_Databases_SyncGroups_SyncMember tests if a specific instance of Servers_Databases_SyncGroups_SyncMember can be assigned to v1beta20211101storage and back losslessly
func RunPropertyAssignmentTestForServers_Databases_SyncGroups_SyncMember(subject Servers_Databases_SyncGroups_SyncMember) string {
	// Copy subject to make sure assignment doesn't modify it
	copied := subject.DeepCopy()

	// Use AssignPropertiesTo() for the first stage of conversion
	var other v20211101s.Servers_Databases_SyncGroups_SyncMember
	err := copied.AssignProperties_To_Servers_Databases_SyncGroups_SyncMember(&other)
	if err != nil {
		return err.Error()
	}

	// Use AssignPropertiesFrom() to convert back to our original type
	var actual Servers_Databases_SyncGroups_SyncMember
	err = actual.AssignProperties_From_Servers_Databases_SyncGroups_SyncMember(&other)
	if err != nil {
		return err.Error()
	}

	// Check for a match
	match := cmp.Equal(subject, actual)
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

func Test_Servers_Databases_SyncGroups_SyncMember_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 20
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of Servers_Databases_SyncGroups_SyncMember via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForServers_Databases_SyncGroups_SyncMember, Servers_Databases_SyncGroups_SyncMemberGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForServers_Databases_SyncGroups_SyncMember runs a test to see if a specific instance of Servers_Databases_SyncGroups_SyncMember round trips to JSON and back losslessly
func RunJSONSerializationTestForServers_Databases_SyncGroups_SyncMember(subject Servers_Databases_SyncGroups_SyncMember) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual Servers_Databases_SyncGroups_SyncMember
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of Servers_Databases_SyncGroups_SyncMember instances for property testing - lazily instantiated by
// Servers_Databases_SyncGroups_SyncMemberGenerator()
var servers_Databases_SyncGroups_SyncMemberGenerator gopter.Gen

// Servers_Databases_SyncGroups_SyncMemberGenerator returns a generator of Servers_Databases_SyncGroups_SyncMember instances for property testing.
func Servers_Databases_SyncGroups_SyncMemberGenerator() gopter.Gen {
	if servers_Databases_SyncGroups_SyncMemberGenerator != nil {
		return servers_Databases_SyncGroups_SyncMemberGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddRelatedPropertyGeneratorsForServers_Databases_SyncGroups_SyncMember(generators)
	servers_Databases_SyncGroups_SyncMemberGenerator = gen.Struct(reflect.TypeOf(Servers_Databases_SyncGroups_SyncMember{}), generators)

	return servers_Databases_SyncGroups_SyncMemberGenerator
}

// AddRelatedPropertyGeneratorsForServers_Databases_SyncGroups_SyncMember is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForServers_Databases_SyncGroups_SyncMember(gens map[string]gopter.Gen) {
	gens["Spec"] = Servers_Databases_SyncGroups_SyncMember_SpecGenerator()
	gens["Status"] = Servers_Databases_SyncGroups_SyncMember_STATUSGenerator()
}

func Test_Servers_Databases_SyncGroups_SyncMember_Spec_WhenPropertiesConverted_RoundTripsWithoutLoss(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip from Servers_Databases_SyncGroups_SyncMember_Spec to Servers_Databases_SyncGroups_SyncMember_Spec via AssignProperties_To_Servers_Databases_SyncGroups_SyncMember_Spec & AssignProperties_From_Servers_Databases_SyncGroups_SyncMember_Spec returns original",
		prop.ForAll(RunPropertyAssignmentTestForServers_Databases_SyncGroups_SyncMember_Spec, Servers_Databases_SyncGroups_SyncMember_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(false, 240, os.Stdout))
}

// RunPropertyAssignmentTestForServers_Databases_SyncGroups_SyncMember_Spec tests if a specific instance of Servers_Databases_SyncGroups_SyncMember_Spec can be assigned to v1beta20211101storage and back losslessly
func RunPropertyAssignmentTestForServers_Databases_SyncGroups_SyncMember_Spec(subject Servers_Databases_SyncGroups_SyncMember_Spec) string {
	// Copy subject to make sure assignment doesn't modify it
	copied := subject.DeepCopy()

	// Use AssignPropertiesTo() for the first stage of conversion
	var other v20211101s.Servers_Databases_SyncGroups_SyncMember_Spec
	err := copied.AssignProperties_To_Servers_Databases_SyncGroups_SyncMember_Spec(&other)
	if err != nil {
		return err.Error()
	}

	// Use AssignPropertiesFrom() to convert back to our original type
	var actual Servers_Databases_SyncGroups_SyncMember_Spec
	err = actual.AssignProperties_From_Servers_Databases_SyncGroups_SyncMember_Spec(&other)
	if err != nil {
		return err.Error()
	}

	// Check for a match
	match := cmp.Equal(subject, actual)
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

func Test_Servers_Databases_SyncGroups_SyncMember_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of Servers_Databases_SyncGroups_SyncMember_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForServers_Databases_SyncGroups_SyncMember_Spec, Servers_Databases_SyncGroups_SyncMember_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForServers_Databases_SyncGroups_SyncMember_Spec runs a test to see if a specific instance of Servers_Databases_SyncGroups_SyncMember_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForServers_Databases_SyncGroups_SyncMember_Spec(subject Servers_Databases_SyncGroups_SyncMember_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual Servers_Databases_SyncGroups_SyncMember_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of Servers_Databases_SyncGroups_SyncMember_Spec instances for property testing - lazily instantiated by
// Servers_Databases_SyncGroups_SyncMember_SpecGenerator()
var servers_Databases_SyncGroups_SyncMember_SpecGenerator gopter.Gen

// Servers_Databases_SyncGroups_SyncMember_SpecGenerator returns a generator of Servers_Databases_SyncGroups_SyncMember_Spec instances for property testing.
func Servers_Databases_SyncGroups_SyncMember_SpecGenerator() gopter.Gen {
	if servers_Databases_SyncGroups_SyncMember_SpecGenerator != nil {
		return servers_Databases_SyncGroups_SyncMember_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForServers_Databases_SyncGroups_SyncMember_Spec(generators)
	servers_Databases_SyncGroups_SyncMember_SpecGenerator = gen.Struct(reflect.TypeOf(Servers_Databases_SyncGroups_SyncMember_Spec{}), generators)

	return servers_Databases_SyncGroups_SyncMember_SpecGenerator
}

// AddIndependentPropertyGeneratorsForServers_Databases_SyncGroups_SyncMember_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForServers_Databases_SyncGroups_SyncMember_Spec(gens map[string]gopter.Gen) {
	gens["AzureName"] = gen.AlphaString()
	gens["DatabaseName"] = gen.PtrOf(gen.AlphaString())
	gens["DatabaseType"] = gen.PtrOf(gen.OneConstOf(SyncMemberProperties_DatabaseType_AzureSqlDatabase, SyncMemberProperties_DatabaseType_SqlServerDatabase))
	gens["Password"] = gen.PtrOf(gen.AlphaString())
	gens["ServerName"] = gen.PtrOf(gen.AlphaString())
	gens["SqlServerDatabaseId"] = gen.PtrOf(gen.AlphaString())
	gens["SyncDirection"] = gen.PtrOf(gen.OneConstOf(SyncMemberProperties_SyncDirection_Bidirectional, SyncMemberProperties_SyncDirection_OneWayHubToMember, SyncMemberProperties_SyncDirection_OneWayMemberToHub))
	gens["UsePrivateLinkConnection"] = gen.PtrOf(gen.Bool())
	gens["UserName"] = gen.PtrOf(gen.AlphaString())
}

func Test_Servers_Databases_SyncGroups_SyncMember_STATUS_WhenPropertiesConverted_RoundTripsWithoutLoss(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip from Servers_Databases_SyncGroups_SyncMember_STATUS to Servers_Databases_SyncGroups_SyncMember_STATUS via AssignProperties_To_Servers_Databases_SyncGroups_SyncMember_STATUS & AssignProperties_From_Servers_Databases_SyncGroups_SyncMember_STATUS returns original",
		prop.ForAll(RunPropertyAssignmentTestForServers_Databases_SyncGroups_SyncMember_STATUS, Servers_Databases_SyncGroups_SyncMember_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(false, 240, os.Stdout))
}

// RunPropertyAssignmentTestForServers_Databases_SyncGroups_SyncMember_STATUS tests if a specific instance of Servers_Databases_SyncGroups_SyncMember_STATUS can be assigned to v1beta20211101storage and back losslessly
func RunPropertyAssignmentTestForServers_Databases_SyncGroups_SyncMember_STATUS(subject Servers_Databases_SyncGroups_SyncMember_STATUS) string {
	// Copy subject to make sure assignment doesn't modify it
	copied := subject.DeepCopy()

	// Use AssignPropertiesTo() for the first stage of conversion
	var other v20211101s.Servers_Databases_SyncGroups_SyncMember_STATUS
	err := copied.AssignProperties_To_Servers_Databases_SyncGroups_SyncMember_STATUS(&other)
	if err != nil {
		return err.Error()
	}

	// Use AssignPropertiesFrom() to convert back to our original type
	var actual Servers_Databases_SyncGroups_SyncMember_STATUS
	err = actual.AssignProperties_From_Servers_Databases_SyncGroups_SyncMember_STATUS(&other)
	if err != nil {
		return err.Error()
	}

	// Check for a match
	match := cmp.Equal(subject, actual)
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

func Test_Servers_Databases_SyncGroups_SyncMember_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of Servers_Databases_SyncGroups_SyncMember_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForServers_Databases_SyncGroups_SyncMember_STATUS, Servers_Databases_SyncGroups_SyncMember_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForServers_Databases_SyncGroups_SyncMember_STATUS runs a test to see if a specific instance of Servers_Databases_SyncGroups_SyncMember_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForServers_Databases_SyncGroups_SyncMember_STATUS(subject Servers_Databases_SyncGroups_SyncMember_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual Servers_Databases_SyncGroups_SyncMember_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of Servers_Databases_SyncGroups_SyncMember_STATUS instances for property testing - lazily instantiated by
// Servers_Databases_SyncGroups_SyncMember_STATUSGenerator()
var servers_Databases_SyncGroups_SyncMember_STATUSGenerator gopter.Gen

// Servers_Databases_SyncGroups_SyncMember_STATUSGenerator returns a generator of Servers_Databases_SyncGroups_SyncMember_STATUS instances for property testing.
func Servers_Databases_SyncGroups_SyncMember_STATUSGenerator() gopter.Gen {
	if servers_Databases_SyncGroups_SyncMember_STATUSGenerator != nil {
		return servers_Databases_SyncGroups_SyncMember_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForServers_Databases_SyncGroups_SyncMember_STATUS(generators)
	servers_Databases_SyncGroups_SyncMember_STATUSGenerator = gen.Struct(reflect.TypeOf(Servers_Databases_SyncGroups_SyncMember_STATUS{}), generators)

	return servers_Databases_SyncGroups_SyncMember_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForServers_Databases_SyncGroups_SyncMember_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForServers_Databases_SyncGroups_SyncMember_STATUS(gens map[string]gopter.Gen) {
	gens["DatabaseName"] = gen.PtrOf(gen.AlphaString())
	gens["DatabaseType"] = gen.PtrOf(gen.OneConstOf(SyncMemberProperties_DatabaseType_STATUS_AzureSqlDatabase, SyncMemberProperties_DatabaseType_STATUS_SqlServerDatabase))
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["Password"] = gen.PtrOf(gen.AlphaString())
	gens["PrivateEndpointName"] = gen.PtrOf(gen.AlphaString())
	gens["ServerName"] = gen.PtrOf(gen.AlphaString())
	gens["SqlServerDatabaseId"] = gen.PtrOf(gen.AlphaString())
	gens["SyncAgentId"] = gen.PtrOf(gen.AlphaString())
	gens["SyncDirection"] = gen.PtrOf(gen.OneConstOf(SyncMemberProperties_SyncDirection_STATUS_Bidirectional, SyncMemberProperties_SyncDirection_STATUS_OneWayHubToMember, SyncMemberProperties_SyncDirection_STATUS_OneWayMemberToHub))
	gens["SyncMemberAzureDatabaseResourceId"] = gen.PtrOf(gen.AlphaString())
	gens["SyncState"] = gen.PtrOf(gen.OneConstOf(
		SyncMemberProperties_SyncState_STATUS_DeProvisionFailed,
		SyncMemberProperties_SyncState_STATUS_DeProvisioned,
		SyncMemberProperties_SyncState_STATUS_DeProvisioning,
		SyncMemberProperties_SyncState_STATUS_DisabledBackupRestore,
		SyncMemberProperties_SyncState_STATUS_DisabledTombstoneCleanup,
		SyncMemberProperties_SyncState_STATUS_ProvisionFailed,
		SyncMemberProperties_SyncState_STATUS_Provisioned,
		SyncMemberProperties_SyncState_STATUS_Provisioning,
		SyncMemberProperties_SyncState_STATUS_ReprovisionFailed,
		SyncMemberProperties_SyncState_STATUS_Reprovisioning,
		SyncMemberProperties_SyncState_STATUS_SyncCancelled,
		SyncMemberProperties_SyncState_STATUS_SyncCancelling,
		SyncMemberProperties_SyncState_STATUS_SyncFailed,
		SyncMemberProperties_SyncState_STATUS_SyncInProgress,
		SyncMemberProperties_SyncState_STATUS_SyncSucceeded,
		SyncMemberProperties_SyncState_STATUS_SyncSucceededWithWarnings,
		SyncMemberProperties_SyncState_STATUS_UnProvisioned,
		SyncMemberProperties_SyncState_STATUS_UnReprovisioned))
	gens["Type"] = gen.PtrOf(gen.AlphaString())
	gens["UsePrivateLinkConnection"] = gen.PtrOf(gen.Bool())
	gens["UserName"] = gen.PtrOf(gen.AlphaString())
}
