// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101

import (
	"encoding/json"
	v20211101s "github.com/Azure/azure-service-operator/v2/api/sql/v1beta20211101storage"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_Servers_Databases_BackupShortTermRetentionPolicy_WhenConvertedToHub_RoundTripsWithoutLoss(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	parameters.MinSuccessfulTests = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip from Servers_Databases_BackupShortTermRetentionPolicy to hub returns original",
		prop.ForAll(RunResourceConversionTestForServers_Databases_BackupShortTermRetentionPolicy, Servers_Databases_BackupShortTermRetentionPolicyGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(false, 240, os.Stdout))
}

// RunResourceConversionTestForServers_Databases_BackupShortTermRetentionPolicy tests if a specific instance of Servers_Databases_BackupShortTermRetentionPolicy round trips to the hub storage version and back losslessly
func RunResourceConversionTestForServers_Databases_BackupShortTermRetentionPolicy(subject Servers_Databases_BackupShortTermRetentionPolicy) string {
	// Copy subject to make sure conversion doesn't modify it
	copied := subject.DeepCopy()

	// Convert to our hub version
	var hub v20211101s.Servers_Databases_BackupShortTermRetentionPolicy
	err := copied.ConvertTo(&hub)
	if err != nil {
		return err.Error()
	}

	// Convert from our hub version
	var actual Servers_Databases_BackupShortTermRetentionPolicy
	err = actual.ConvertFrom(&hub)
	if err != nil {
		return err.Error()
	}

	// Compare actual with what we started with
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

func Test_Servers_Databases_BackupShortTermRetentionPolicy_WhenPropertiesConverted_RoundTripsWithoutLoss(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip from Servers_Databases_BackupShortTermRetentionPolicy to Servers_Databases_BackupShortTermRetentionPolicy via AssignProperties_To_Servers_Databases_BackupShortTermRetentionPolicy & AssignProperties_From_Servers_Databases_BackupShortTermRetentionPolicy returns original",
		prop.ForAll(RunPropertyAssignmentTestForServers_Databases_BackupShortTermRetentionPolicy, Servers_Databases_BackupShortTermRetentionPolicyGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(false, 240, os.Stdout))
}

// RunPropertyAssignmentTestForServers_Databases_BackupShortTermRetentionPolicy tests if a specific instance of Servers_Databases_BackupShortTermRetentionPolicy can be assigned to v1beta20211101storage and back losslessly
func RunPropertyAssignmentTestForServers_Databases_BackupShortTermRetentionPolicy(subject Servers_Databases_BackupShortTermRetentionPolicy) string {
	// Copy subject to make sure assignment doesn't modify it
	copied := subject.DeepCopy()

	// Use AssignPropertiesTo() for the first stage of conversion
	var other v20211101s.Servers_Databases_BackupShortTermRetentionPolicy
	err := copied.AssignProperties_To_Servers_Databases_BackupShortTermRetentionPolicy(&other)
	if err != nil {
		return err.Error()
	}

	// Use AssignPropertiesFrom() to convert back to our original type
	var actual Servers_Databases_BackupShortTermRetentionPolicy
	err = actual.AssignProperties_From_Servers_Databases_BackupShortTermRetentionPolicy(&other)
	if err != nil {
		return err.Error()
	}

	// Check for a match
	match := cmp.Equal(subject, actual)
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

func Test_Servers_Databases_BackupShortTermRetentionPolicy_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 20
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of Servers_Databases_BackupShortTermRetentionPolicy via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForServers_Databases_BackupShortTermRetentionPolicy, Servers_Databases_BackupShortTermRetentionPolicyGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForServers_Databases_BackupShortTermRetentionPolicy runs a test to see if a specific instance of Servers_Databases_BackupShortTermRetentionPolicy round trips to JSON and back losslessly
func RunJSONSerializationTestForServers_Databases_BackupShortTermRetentionPolicy(subject Servers_Databases_BackupShortTermRetentionPolicy) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual Servers_Databases_BackupShortTermRetentionPolicy
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of Servers_Databases_BackupShortTermRetentionPolicy instances for property testing - lazily instantiated by
// Servers_Databases_BackupShortTermRetentionPolicyGenerator()
var servers_Databases_BackupShortTermRetentionPolicyGenerator gopter.Gen

// Servers_Databases_BackupShortTermRetentionPolicyGenerator returns a generator of Servers_Databases_BackupShortTermRetentionPolicy instances for property testing.
func Servers_Databases_BackupShortTermRetentionPolicyGenerator() gopter.Gen {
	if servers_Databases_BackupShortTermRetentionPolicyGenerator != nil {
		return servers_Databases_BackupShortTermRetentionPolicyGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddRelatedPropertyGeneratorsForServers_Databases_BackupShortTermRetentionPolicy(generators)
	servers_Databases_BackupShortTermRetentionPolicyGenerator = gen.Struct(reflect.TypeOf(Servers_Databases_BackupShortTermRetentionPolicy{}), generators)

	return servers_Databases_BackupShortTermRetentionPolicyGenerator
}

// AddRelatedPropertyGeneratorsForServers_Databases_BackupShortTermRetentionPolicy is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForServers_Databases_BackupShortTermRetentionPolicy(gens map[string]gopter.Gen) {
	gens["Spec"] = Servers_Databases_BackupShortTermRetentionPolicy_SpecGenerator()
	gens["Status"] = Servers_Databases_BackupShortTermRetentionPolicy_STATUSGenerator()
}

func Test_Servers_Databases_BackupShortTermRetentionPolicy_Spec_WhenPropertiesConverted_RoundTripsWithoutLoss(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip from Servers_Databases_BackupShortTermRetentionPolicy_Spec to Servers_Databases_BackupShortTermRetentionPolicy_Spec via AssignProperties_To_Servers_Databases_BackupShortTermRetentionPolicy_Spec & AssignProperties_From_Servers_Databases_BackupShortTermRetentionPolicy_Spec returns original",
		prop.ForAll(RunPropertyAssignmentTestForServers_Databases_BackupShortTermRetentionPolicy_Spec, Servers_Databases_BackupShortTermRetentionPolicy_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(false, 240, os.Stdout))
}

// RunPropertyAssignmentTestForServers_Databases_BackupShortTermRetentionPolicy_Spec tests if a specific instance of Servers_Databases_BackupShortTermRetentionPolicy_Spec can be assigned to v1beta20211101storage and back losslessly
func RunPropertyAssignmentTestForServers_Databases_BackupShortTermRetentionPolicy_Spec(subject Servers_Databases_BackupShortTermRetentionPolicy_Spec) string {
	// Copy subject to make sure assignment doesn't modify it
	copied := subject.DeepCopy()

	// Use AssignPropertiesTo() for the first stage of conversion
	var other v20211101s.Servers_Databases_BackupShortTermRetentionPolicy_Spec
	err := copied.AssignProperties_To_Servers_Databases_BackupShortTermRetentionPolicy_Spec(&other)
	if err != nil {
		return err.Error()
	}

	// Use AssignPropertiesFrom() to convert back to our original type
	var actual Servers_Databases_BackupShortTermRetentionPolicy_Spec
	err = actual.AssignProperties_From_Servers_Databases_BackupShortTermRetentionPolicy_Spec(&other)
	if err != nil {
		return err.Error()
	}

	// Check for a match
	match := cmp.Equal(subject, actual)
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

func Test_Servers_Databases_BackupShortTermRetentionPolicy_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of Servers_Databases_BackupShortTermRetentionPolicy_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForServers_Databases_BackupShortTermRetentionPolicy_Spec, Servers_Databases_BackupShortTermRetentionPolicy_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForServers_Databases_BackupShortTermRetentionPolicy_Spec runs a test to see if a specific instance of Servers_Databases_BackupShortTermRetentionPolicy_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForServers_Databases_BackupShortTermRetentionPolicy_Spec(subject Servers_Databases_BackupShortTermRetentionPolicy_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual Servers_Databases_BackupShortTermRetentionPolicy_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of Servers_Databases_BackupShortTermRetentionPolicy_Spec instances for property testing - lazily
// instantiated by Servers_Databases_BackupShortTermRetentionPolicy_SpecGenerator()
var servers_Databases_BackupShortTermRetentionPolicy_SpecGenerator gopter.Gen

// Servers_Databases_BackupShortTermRetentionPolicy_SpecGenerator returns a generator of Servers_Databases_BackupShortTermRetentionPolicy_Spec instances for property testing.
func Servers_Databases_BackupShortTermRetentionPolicy_SpecGenerator() gopter.Gen {
	if servers_Databases_BackupShortTermRetentionPolicy_SpecGenerator != nil {
		return servers_Databases_BackupShortTermRetentionPolicy_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForServers_Databases_BackupShortTermRetentionPolicy_Spec(generators)
	servers_Databases_BackupShortTermRetentionPolicy_SpecGenerator = gen.Struct(reflect.TypeOf(Servers_Databases_BackupShortTermRetentionPolicy_Spec{}), generators)

	return servers_Databases_BackupShortTermRetentionPolicy_SpecGenerator
}

// AddIndependentPropertyGeneratorsForServers_Databases_BackupShortTermRetentionPolicy_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForServers_Databases_BackupShortTermRetentionPolicy_Spec(gens map[string]gopter.Gen) {
	gens["DiffBackupIntervalInHours"] = gen.PtrOf(gen.OneConstOf(BackupShortTermRetentionPolicyProperties_DiffBackupIntervalInHours_12, BackupShortTermRetentionPolicyProperties_DiffBackupIntervalInHours_24))
	gens["RetentionDays"] = gen.PtrOf(gen.Int())
}

func Test_Servers_Databases_BackupShortTermRetentionPolicy_STATUS_WhenPropertiesConverted_RoundTripsWithoutLoss(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MaxSize = 10
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip from Servers_Databases_BackupShortTermRetentionPolicy_STATUS to Servers_Databases_BackupShortTermRetentionPolicy_STATUS via AssignProperties_To_Servers_Databases_BackupShortTermRetentionPolicy_STATUS & AssignProperties_From_Servers_Databases_BackupShortTermRetentionPolicy_STATUS returns original",
		prop.ForAll(RunPropertyAssignmentTestForServers_Databases_BackupShortTermRetentionPolicy_STATUS, Servers_Databases_BackupShortTermRetentionPolicy_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(false, 240, os.Stdout))
}

// RunPropertyAssignmentTestForServers_Databases_BackupShortTermRetentionPolicy_STATUS tests if a specific instance of Servers_Databases_BackupShortTermRetentionPolicy_STATUS can be assigned to v1beta20211101storage and back losslessly
func RunPropertyAssignmentTestForServers_Databases_BackupShortTermRetentionPolicy_STATUS(subject Servers_Databases_BackupShortTermRetentionPolicy_STATUS) string {
	// Copy subject to make sure assignment doesn't modify it
	copied := subject.DeepCopy()

	// Use AssignPropertiesTo() for the first stage of conversion
	var other v20211101s.Servers_Databases_BackupShortTermRetentionPolicy_STATUS
	err := copied.AssignProperties_To_Servers_Databases_BackupShortTermRetentionPolicy_STATUS(&other)
	if err != nil {
		return err.Error()
	}

	// Use AssignPropertiesFrom() to convert back to our original type
	var actual Servers_Databases_BackupShortTermRetentionPolicy_STATUS
	err = actual.AssignProperties_From_Servers_Databases_BackupShortTermRetentionPolicy_STATUS(&other)
	if err != nil {
		return err.Error()
	}

	// Check for a match
	match := cmp.Equal(subject, actual)
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

func Test_Servers_Databases_BackupShortTermRetentionPolicy_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of Servers_Databases_BackupShortTermRetentionPolicy_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForServers_Databases_BackupShortTermRetentionPolicy_STATUS, Servers_Databases_BackupShortTermRetentionPolicy_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForServers_Databases_BackupShortTermRetentionPolicy_STATUS runs a test to see if a specific instance of Servers_Databases_BackupShortTermRetentionPolicy_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForServers_Databases_BackupShortTermRetentionPolicy_STATUS(subject Servers_Databases_BackupShortTermRetentionPolicy_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual Servers_Databases_BackupShortTermRetentionPolicy_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of Servers_Databases_BackupShortTermRetentionPolicy_STATUS instances for property testing - lazily
// instantiated by Servers_Databases_BackupShortTermRetentionPolicy_STATUSGenerator()
var servers_Databases_BackupShortTermRetentionPolicy_STATUSGenerator gopter.Gen

// Servers_Databases_BackupShortTermRetentionPolicy_STATUSGenerator returns a generator of Servers_Databases_BackupShortTermRetentionPolicy_STATUS instances for property testing.
func Servers_Databases_BackupShortTermRetentionPolicy_STATUSGenerator() gopter.Gen {
	if servers_Databases_BackupShortTermRetentionPolicy_STATUSGenerator != nil {
		return servers_Databases_BackupShortTermRetentionPolicy_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForServers_Databases_BackupShortTermRetentionPolicy_STATUS(generators)
	servers_Databases_BackupShortTermRetentionPolicy_STATUSGenerator = gen.Struct(reflect.TypeOf(Servers_Databases_BackupShortTermRetentionPolicy_STATUS{}), generators)

	return servers_Databases_BackupShortTermRetentionPolicy_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForServers_Databases_BackupShortTermRetentionPolicy_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForServers_Databases_BackupShortTermRetentionPolicy_STATUS(gens map[string]gopter.Gen) {
	gens["DiffBackupIntervalInHours"] = gen.PtrOf(gen.OneConstOf(BackupShortTermRetentionPolicyProperties_DiffBackupIntervalInHours_STATUS_12, BackupShortTermRetentionPolicyProperties_DiffBackupIntervalInHours_STATUS_24))
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["RetentionDays"] = gen.PtrOf(gen.Int())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}
