// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101

import "github.com/Azure/azure-service-operator/v2/pkg/genruntime"

type Servers_Databases_WorkloadGroups_WorkloadClassifier_Spec_ARM struct {
	Name string `json:"name,omitempty"`

	// Properties: Resource properties.
	Properties *WorkloadClassifierProperties_ARM `json:"properties,omitempty"`
}

var _ genruntime.ARMResourceSpec = &Servers_Databases_WorkloadGroups_WorkloadClassifier_Spec_ARM{}

// GetAPIVersion returns the ARM API version of the resource. This is always "2021-11-01"
func (classifier Servers_Databases_WorkloadGroups_WorkloadClassifier_Spec_ARM) GetAPIVersion() string {
	return string(APIVersion_Value)
}

// GetName returns the Name of the resource
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier_Spec_ARM) GetName() string {
	return classifier.Name
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Sql/servers/databases/workloadGroups/workloadClassifiers"
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier_Spec_ARM) GetType() string {
	return "Microsoft.Sql/servers/databases/workloadGroups/workloadClassifiers"
}

// Workload classifier definition. For more information look at sys.workload_management_workload_classifiers (DMV).
type WorkloadClassifierProperties_ARM struct {
	// Context: The workload classifier context.
	Context *string `json:"context,omitempty"`

	// EndTime: The workload classifier end time for classification.
	EndTime *string `json:"endTime,omitempty"`

	// Importance: The workload classifier importance.
	Importance *string `json:"importance,omitempty"`

	// Label: The workload classifier label.
	Label *string `json:"label,omitempty"`

	// MemberName: The workload classifier member name.
	MemberName *string `json:"memberName,omitempty"`

	// StartTime: The workload classifier start time for classification.
	StartTime *string `json:"startTime,omitempty"`
}
