// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101

type Servers_SyncAgent_STATUS_ARM struct {
	// Id: Resource ID.
	Id *string `json:"id,omitempty"`

	// Name: Resource name.
	Name *string `json:"name,omitempty"`

	// Properties: Resource properties.
	Properties *SyncAgentProperties_STATUS_ARM `json:"properties,omitempty"`

	// Type: Resource type.
	Type *string `json:"type,omitempty"`
}

// Properties of an Azure SQL Database sync agent.
type SyncAgentProperties_STATUS_ARM struct {
	// ExpiryTime: Expiration time of the sync agent version.
	ExpiryTime *string `json:"expiryTime,omitempty"`

	// IsUpToDate: If the sync agent version is up to date.
	IsUpToDate *bool `json:"isUpToDate,omitempty"`

	// LastAliveTime: Last alive time of the sync agent.
	LastAliveTime *string `json:"lastAliveTime,omitempty"`

	// Name: Name of the sync agent.
	Name *string `json:"name,omitempty"`

	// State: State of the sync agent.
	State *SyncAgentProperties_State_STATUS `json:"state,omitempty"`

	// SyncDatabaseId: ARM resource id of the sync database in the sync agent.
	SyncDatabaseId *string `json:"syncDatabaseId,omitempty"`

	// Version: Version of the sync agent.
	Version *string `json:"version,omitempty"`
}
