// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101

type Servers_Databases_SyncGroup_STATUS_ARM struct {
	// Id: Resource ID.
	Id *string `json:"id,omitempty"`

	// Name: Resource name.
	Name *string `json:"name,omitempty"`

	// Properties: Resource properties.
	Properties *SyncGroupProperties_STATUS_ARM `json:"properties,omitempty"`

	// Sku: The name and capacity of the SKU.
	Sku *Sku_STATUS_ARM `json:"sku,omitempty"`

	// Type: Resource type.
	Type *string `json:"type,omitempty"`
}

// Properties of a sync group.
type SyncGroupProperties_STATUS_ARM struct {
	// ConflictLoggingRetentionInDays: Conflict logging retention period.
	ConflictLoggingRetentionInDays *int `json:"conflictLoggingRetentionInDays,omitempty"`

	// ConflictResolutionPolicy: Conflict resolution policy of the sync group.
	ConflictResolutionPolicy *SyncGroupProperties_ConflictResolutionPolicy_STATUS `json:"conflictResolutionPolicy,omitempty"`

	// EnableConflictLogging: If conflict logging is enabled.
	EnableConflictLogging *bool `json:"enableConflictLogging,omitempty"`

	// HubDatabaseUserName: User name for the sync group hub database credential.
	HubDatabaseUserName *string `json:"hubDatabaseUserName,omitempty"`

	// Interval: Sync interval of the sync group.
	Interval *int `json:"interval,omitempty"`

	// LastSyncTime: Last sync time of the sync group.
	LastSyncTime *string `json:"lastSyncTime,omitempty"`

	// PrivateEndpointName: Private endpoint name of the sync group if use private link connection is enabled.
	PrivateEndpointName *string `json:"privateEndpointName,omitempty"`

	// Schema: Sync schema of the sync group.
	Schema *SyncGroupSchema_STATUS_ARM `json:"schema,omitempty"`

	// SyncDatabaseId: ARM resource id of the sync database in the sync group.
	SyncDatabaseId *string `json:"syncDatabaseId,omitempty"`

	// SyncState: Sync state of the sync group.
	SyncState *SyncGroupProperties_SyncState_STATUS `json:"syncState,omitempty"`

	// UsePrivateLinkConnection: If use private link connection is enabled.
	UsePrivateLinkConnection *bool `json:"usePrivateLinkConnection,omitempty"`
}

// Properties of sync group schema.
type SyncGroupSchema_STATUS_ARM struct {
	// MasterSyncMemberName: Name of master sync member where the schema is from.
	MasterSyncMemberName *string `json:"masterSyncMemberName,omitempty"`

	// Tables: List of tables in sync group schema.
	Tables []SyncGroupSchemaTable_STATUS_ARM `json:"tables,omitempty"`
}

// Properties of table in sync group schema.
type SyncGroupSchemaTable_STATUS_ARM struct {
	// Columns: List of columns in sync group schema.
	Columns []SyncGroupSchemaTableColumn_STATUS_ARM `json:"columns,omitempty"`

	// QuotedName: Quoted name of sync group schema table.
	QuotedName *string `json:"quotedName,omitempty"`
}

// Properties of column in sync group table.
type SyncGroupSchemaTableColumn_STATUS_ARM struct {
	// DataSize: Data size of the column.
	DataSize *string `json:"dataSize,omitempty"`

	// DataType: Data type of the column.
	DataType *string `json:"dataType,omitempty"`

	// QuotedName: Quoted name of sync group table column.
	QuotedName *string `json:"quotedName,omitempty"`
}
