// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101

type Servers_DnsAliase_STATUS_ARM struct {
	// Id: Resource ID.
	Id *string `json:"id,omitempty"`

	// Name: Resource name.
	Name *string `json:"name,omitempty"`

	// Properties: Resource properties.
	Properties *ServerDnsAliasProperties_STATUS_ARM `json:"properties,omitempty"`

	// Type: Resource type.
	Type *string `json:"type,omitempty"`
}

// Properties of a server DNS alias.
type ServerDnsAliasProperties_STATUS_ARM struct {
	// AzureDnsRecord: The fully qualified DNS record for alias
	AzureDnsRecord *string `json:"azureDnsRecord,omitempty"`
}
