// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101

type Servers_Databases_SyncGroups_SyncMember_STATUS_ARM struct {
	// Id: Resource ID.
	Id *string `json:"id,omitempty"`

	// Name: Resource name.
	Name *string `json:"name,omitempty"`

	// Properties: Resource properties.
	Properties *SyncMemberProperties_STATUS_ARM `json:"properties,omitempty"`

	// Type: Resource type.
	Type *string `json:"type,omitempty"`
}

// Properties of a sync member.
type SyncMemberProperties_STATUS_ARM struct {
	// DatabaseName: Database name of the member database in the sync member.
	DatabaseName *string `json:"databaseName,omitempty"`

	// DatabaseType: Database type of the sync member.
	DatabaseType *SyncMemberProperties_DatabaseType_STATUS `json:"databaseType,omitempty"`

	// Password: Password of the member database in the sync member.
	Password *string `json:"password,omitempty"`

	// PrivateEndpointName: Private endpoint name of the sync member if use private link connection is enabled, for sync
	// members in Azure.
	PrivateEndpointName *string `json:"privateEndpointName,omitempty"`

	// ServerName: Server name of the member database in the sync member
	ServerName *string `json:"serverName,omitempty"`

	// SqlServerDatabaseId: SQL Server database id of the sync member.
	SqlServerDatabaseId *string `json:"sqlServerDatabaseId,omitempty"`

	// SyncAgentId: ARM resource id of the sync agent in the sync member.
	SyncAgentId *string `json:"syncAgentId,omitempty"`

	// SyncDirection: Sync direction of the sync member.
	SyncDirection *SyncMemberProperties_SyncDirection_STATUS `json:"syncDirection,omitempty"`

	// SyncMemberAzureDatabaseResourceId: ARM resource id of the sync member logical database, for sync members in Azure.
	SyncMemberAzureDatabaseResourceId *string `json:"syncMemberAzureDatabaseResourceId,omitempty"`

	// SyncState: Sync state of the sync member.
	SyncState *SyncMemberProperties_SyncState_STATUS `json:"syncState,omitempty"`

	// UsePrivateLinkConnection: Whether to use private link connection.
	UsePrivateLinkConnection *bool `json:"usePrivateLinkConnection,omitempty"`

	// UserName: User name of the member database in the sync member.
	UserName *string `json:"userName,omitempty"`
}
