// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101storage

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_ManagedInstances_DistributedAvailabilityGroup_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 20
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of ManagedInstances_DistributedAvailabilityGroup via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForManagedInstances_DistributedAvailabilityGroup, ManagedInstances_DistributedAvailabilityGroupGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForManagedInstances_DistributedAvailabilityGroup runs a test to see if a specific instance of ManagedInstances_DistributedAvailabilityGroup round trips to JSON and back losslessly
func RunJSONSerializationTestForManagedInstances_DistributedAvailabilityGroup(subject ManagedInstances_DistributedAvailabilityGroup) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual ManagedInstances_DistributedAvailabilityGroup
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of ManagedInstances_DistributedAvailabilityGroup instances for property testing - lazily instantiated by
// ManagedInstances_DistributedAvailabilityGroupGenerator()
var managedInstances_DistributedAvailabilityGroupGenerator gopter.Gen

// ManagedInstances_DistributedAvailabilityGroupGenerator returns a generator of ManagedInstances_DistributedAvailabilityGroup instances for property testing.
func ManagedInstances_DistributedAvailabilityGroupGenerator() gopter.Gen {
	if managedInstances_DistributedAvailabilityGroupGenerator != nil {
		return managedInstances_DistributedAvailabilityGroupGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddRelatedPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup(generators)
	managedInstances_DistributedAvailabilityGroupGenerator = gen.Struct(reflect.TypeOf(ManagedInstances_DistributedAvailabilityGroup{}), generators)

	return managedInstances_DistributedAvailabilityGroupGenerator
}

// AddRelatedPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup(gens map[string]gopter.Gen) {
	gens["Spec"] = ManagedInstances_DistributedAvailabilityGroup_SpecGenerator()
	gens["Status"] = ManagedInstances_DistributedAvailabilityGroup_STATUSGenerator()
}

func Test_ManagedInstances_DistributedAvailabilityGroup_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of ManagedInstances_DistributedAvailabilityGroup_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForManagedInstances_DistributedAvailabilityGroup_Spec, ManagedInstances_DistributedAvailabilityGroup_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForManagedInstances_DistributedAvailabilityGroup_Spec runs a test to see if a specific instance of ManagedInstances_DistributedAvailabilityGroup_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForManagedInstances_DistributedAvailabilityGroup_Spec(subject ManagedInstances_DistributedAvailabilityGroup_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual ManagedInstances_DistributedAvailabilityGroup_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of ManagedInstances_DistributedAvailabilityGroup_Spec instances for property testing - lazily instantiated
// by ManagedInstances_DistributedAvailabilityGroup_SpecGenerator()
var managedInstances_DistributedAvailabilityGroup_SpecGenerator gopter.Gen

// ManagedInstances_DistributedAvailabilityGroup_SpecGenerator returns a generator of ManagedInstances_DistributedAvailabilityGroup_Spec instances for property testing.
func ManagedInstances_DistributedAvailabilityGroup_SpecGenerator() gopter.Gen {
	if managedInstances_DistributedAvailabilityGroup_SpecGenerator != nil {
		return managedInstances_DistributedAvailabilityGroup_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup_Spec(generators)
	managedInstances_DistributedAvailabilityGroup_SpecGenerator = gen.Struct(reflect.TypeOf(ManagedInstances_DistributedAvailabilityGroup_Spec{}), generators)

	return managedInstances_DistributedAvailabilityGroup_SpecGenerator
}

// AddIndependentPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup_Spec(gens map[string]gopter.Gen) {
	gens["AzureName"] = gen.AlphaString()
	gens["OriginalVersion"] = gen.AlphaString()
	gens["PrimaryAvailabilityGroupName"] = gen.PtrOf(gen.AlphaString())
	gens["ReplicationMode"] = gen.PtrOf(gen.AlphaString())
	gens["SecondaryAvailabilityGroupName"] = gen.PtrOf(gen.AlphaString())
	gens["SourceEndpoint"] = gen.PtrOf(gen.AlphaString())
	gens["TargetDatabase"] = gen.PtrOf(gen.AlphaString())
}

func Test_ManagedInstances_DistributedAvailabilityGroup_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of ManagedInstances_DistributedAvailabilityGroup_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForManagedInstances_DistributedAvailabilityGroup_STATUS, ManagedInstances_DistributedAvailabilityGroup_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForManagedInstances_DistributedAvailabilityGroup_STATUS runs a test to see if a specific instance of ManagedInstances_DistributedAvailabilityGroup_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForManagedInstances_DistributedAvailabilityGroup_STATUS(subject ManagedInstances_DistributedAvailabilityGroup_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual ManagedInstances_DistributedAvailabilityGroup_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of ManagedInstances_DistributedAvailabilityGroup_STATUS instances for property testing - lazily
// instantiated by ManagedInstances_DistributedAvailabilityGroup_STATUSGenerator()
var managedInstances_DistributedAvailabilityGroup_STATUSGenerator gopter.Gen

// ManagedInstances_DistributedAvailabilityGroup_STATUSGenerator returns a generator of ManagedInstances_DistributedAvailabilityGroup_STATUS instances for property testing.
func ManagedInstances_DistributedAvailabilityGroup_STATUSGenerator() gopter.Gen {
	if managedInstances_DistributedAvailabilityGroup_STATUSGenerator != nil {
		return managedInstances_DistributedAvailabilityGroup_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup_STATUS(generators)
	managedInstances_DistributedAvailabilityGroup_STATUSGenerator = gen.Struct(reflect.TypeOf(ManagedInstances_DistributedAvailabilityGroup_STATUS{}), generators)

	return managedInstances_DistributedAvailabilityGroup_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForManagedInstances_DistributedAvailabilityGroup_STATUS(gens map[string]gopter.Gen) {
	gens["DistributedAvailabilityGroupId"] = gen.PtrOf(gen.AlphaString())
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["LastHardenedLsn"] = gen.PtrOf(gen.AlphaString())
	gens["LinkState"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["PrimaryAvailabilityGroupName"] = gen.PtrOf(gen.AlphaString())
	gens["ReplicationMode"] = gen.PtrOf(gen.AlphaString())
	gens["SecondaryAvailabilityGroupName"] = gen.PtrOf(gen.AlphaString())
	gens["SourceEndpoint"] = gen.PtrOf(gen.AlphaString())
	gens["SourceReplicaId"] = gen.PtrOf(gen.AlphaString())
	gens["TargetDatabase"] = gen.PtrOf(gen.AlphaString())
	gens["TargetReplicaId"] = gen.PtrOf(gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}
