// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101storage

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_ServersDatabasesGeoBackupPolicy_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 20
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of ServersDatabasesGeoBackupPolicy via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForServersDatabasesGeoBackupPolicy, ServersDatabasesGeoBackupPolicyGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForServersDatabasesGeoBackupPolicy runs a test to see if a specific instance of ServersDatabasesGeoBackupPolicy round trips to JSON and back losslessly
func RunJSONSerializationTestForServersDatabasesGeoBackupPolicy(subject ServersDatabasesGeoBackupPolicy) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual ServersDatabasesGeoBackupPolicy
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of ServersDatabasesGeoBackupPolicy instances for property testing - lazily instantiated by
// ServersDatabasesGeoBackupPolicyGenerator()
var serversDatabasesGeoBackupPolicyGenerator gopter.Gen

// ServersDatabasesGeoBackupPolicyGenerator returns a generator of ServersDatabasesGeoBackupPolicy instances for property testing.
func ServersDatabasesGeoBackupPolicyGenerator() gopter.Gen {
	if serversDatabasesGeoBackupPolicyGenerator != nil {
		return serversDatabasesGeoBackupPolicyGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddRelatedPropertyGeneratorsForServersDatabasesGeoBackupPolicy(generators)
	serversDatabasesGeoBackupPolicyGenerator = gen.Struct(reflect.TypeOf(ServersDatabasesGeoBackupPolicy{}), generators)

	return serversDatabasesGeoBackupPolicyGenerator
}

// AddRelatedPropertyGeneratorsForServersDatabasesGeoBackupPolicy is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForServersDatabasesGeoBackupPolicy(gens map[string]gopter.Gen) {
	gens["Spec"] = Servers_Databases_GeoBackupPolicy_SpecGenerator()
	gens["Status"] = Servers_Databases_GeoBackupPolicy_STATUSGenerator()
}

func Test_Servers_Databases_GeoBackupPolicy_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of Servers_Databases_GeoBackupPolicy_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForServers_Databases_GeoBackupPolicy_Spec, Servers_Databases_GeoBackupPolicy_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForServers_Databases_GeoBackupPolicy_Spec runs a test to see if a specific instance of Servers_Databases_GeoBackupPolicy_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForServers_Databases_GeoBackupPolicy_Spec(subject Servers_Databases_GeoBackupPolicy_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual Servers_Databases_GeoBackupPolicy_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of Servers_Databases_GeoBackupPolicy_Spec instances for property testing - lazily instantiated by
// Servers_Databases_GeoBackupPolicy_SpecGenerator()
var servers_Databases_GeoBackupPolicy_SpecGenerator gopter.Gen

// Servers_Databases_GeoBackupPolicy_SpecGenerator returns a generator of Servers_Databases_GeoBackupPolicy_Spec instances for property testing.
func Servers_Databases_GeoBackupPolicy_SpecGenerator() gopter.Gen {
	if servers_Databases_GeoBackupPolicy_SpecGenerator != nil {
		return servers_Databases_GeoBackupPolicy_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForServers_Databases_GeoBackupPolicy_Spec(generators)
	servers_Databases_GeoBackupPolicy_SpecGenerator = gen.Struct(reflect.TypeOf(Servers_Databases_GeoBackupPolicy_Spec{}), generators)

	return servers_Databases_GeoBackupPolicy_SpecGenerator
}

// AddIndependentPropertyGeneratorsForServers_Databases_GeoBackupPolicy_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForServers_Databases_GeoBackupPolicy_Spec(gens map[string]gopter.Gen) {
	gens["OriginalVersion"] = gen.AlphaString()
	gens["State"] = gen.PtrOf(gen.AlphaString())
}

func Test_Servers_Databases_GeoBackupPolicy_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of Servers_Databases_GeoBackupPolicy_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForServers_Databases_GeoBackupPolicy_STATUS, Servers_Databases_GeoBackupPolicy_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForServers_Databases_GeoBackupPolicy_STATUS runs a test to see if a specific instance of Servers_Databases_GeoBackupPolicy_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForServers_Databases_GeoBackupPolicy_STATUS(subject Servers_Databases_GeoBackupPolicy_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual Servers_Databases_GeoBackupPolicy_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of Servers_Databases_GeoBackupPolicy_STATUS instances for property testing - lazily instantiated by
// Servers_Databases_GeoBackupPolicy_STATUSGenerator()
var servers_Databases_GeoBackupPolicy_STATUSGenerator gopter.Gen

// Servers_Databases_GeoBackupPolicy_STATUSGenerator returns a generator of Servers_Databases_GeoBackupPolicy_STATUS instances for property testing.
func Servers_Databases_GeoBackupPolicy_STATUSGenerator() gopter.Gen {
	if servers_Databases_GeoBackupPolicy_STATUSGenerator != nil {
		return servers_Databases_GeoBackupPolicy_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForServers_Databases_GeoBackupPolicy_STATUS(generators)
	servers_Databases_GeoBackupPolicy_STATUSGenerator = gen.Struct(reflect.TypeOf(Servers_Databases_GeoBackupPolicy_STATUS{}), generators)

	return servers_Databases_GeoBackupPolicy_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForServers_Databases_GeoBackupPolicy_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForServers_Databases_GeoBackupPolicy_STATUS(gens map[string]gopter.Gen) {
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Kind"] = gen.PtrOf(gen.AlphaString())
	gens["Location"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["State"] = gen.PtrOf(gen.AlphaString())
	gens["StorageType"] = gen.PtrOf(gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}
