// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101storage

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_ServersDatabasesExtendedAuditingSetting_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 20
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of ServersDatabasesExtendedAuditingSetting via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForServersDatabasesExtendedAuditingSetting, ServersDatabasesExtendedAuditingSettingGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForServersDatabasesExtendedAuditingSetting runs a test to see if a specific instance of ServersDatabasesExtendedAuditingSetting round trips to JSON and back losslessly
func RunJSONSerializationTestForServersDatabasesExtendedAuditingSetting(subject ServersDatabasesExtendedAuditingSetting) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual ServersDatabasesExtendedAuditingSetting
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of ServersDatabasesExtendedAuditingSetting instances for property testing - lazily instantiated by
// ServersDatabasesExtendedAuditingSettingGenerator()
var serversDatabasesExtendedAuditingSettingGenerator gopter.Gen

// ServersDatabasesExtendedAuditingSettingGenerator returns a generator of ServersDatabasesExtendedAuditingSetting instances for property testing.
func ServersDatabasesExtendedAuditingSettingGenerator() gopter.Gen {
	if serversDatabasesExtendedAuditingSettingGenerator != nil {
		return serversDatabasesExtendedAuditingSettingGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddRelatedPropertyGeneratorsForServersDatabasesExtendedAuditingSetting(generators)
	serversDatabasesExtendedAuditingSettingGenerator = gen.Struct(reflect.TypeOf(ServersDatabasesExtendedAuditingSetting{}), generators)

	return serversDatabasesExtendedAuditingSettingGenerator
}

// AddRelatedPropertyGeneratorsForServersDatabasesExtendedAuditingSetting is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForServersDatabasesExtendedAuditingSetting(gens map[string]gopter.Gen) {
	gens["Spec"] = Servers_Databases_ExtendedAuditingSetting_SpecGenerator()
	gens["Status"] = Servers_Databases_ExtendedAuditingSetting_STATUSGenerator()
}

func Test_Servers_Databases_ExtendedAuditingSetting_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of Servers_Databases_ExtendedAuditingSetting_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForServers_Databases_ExtendedAuditingSetting_Spec, Servers_Databases_ExtendedAuditingSetting_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForServers_Databases_ExtendedAuditingSetting_Spec runs a test to see if a specific instance of Servers_Databases_ExtendedAuditingSetting_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForServers_Databases_ExtendedAuditingSetting_Spec(subject Servers_Databases_ExtendedAuditingSetting_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual Servers_Databases_ExtendedAuditingSetting_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of Servers_Databases_ExtendedAuditingSetting_Spec instances for property testing - lazily instantiated by
// Servers_Databases_ExtendedAuditingSetting_SpecGenerator()
var servers_Databases_ExtendedAuditingSetting_SpecGenerator gopter.Gen

// Servers_Databases_ExtendedAuditingSetting_SpecGenerator returns a generator of Servers_Databases_ExtendedAuditingSetting_Spec instances for property testing.
func Servers_Databases_ExtendedAuditingSetting_SpecGenerator() gopter.Gen {
	if servers_Databases_ExtendedAuditingSetting_SpecGenerator != nil {
		return servers_Databases_ExtendedAuditingSetting_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForServers_Databases_ExtendedAuditingSetting_Spec(generators)
	servers_Databases_ExtendedAuditingSetting_SpecGenerator = gen.Struct(reflect.TypeOf(Servers_Databases_ExtendedAuditingSetting_Spec{}), generators)

	return servers_Databases_ExtendedAuditingSetting_SpecGenerator
}

// AddIndependentPropertyGeneratorsForServers_Databases_ExtendedAuditingSetting_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForServers_Databases_ExtendedAuditingSetting_Spec(gens map[string]gopter.Gen) {
	gens["AuditActionsAndGroups"] = gen.SliceOf(gen.AlphaString())
	gens["IsAzureMonitorTargetEnabled"] = gen.PtrOf(gen.Bool())
	gens["IsManagedIdentityInUse"] = gen.PtrOf(gen.Bool())
	gens["IsStorageSecondaryKeyInUse"] = gen.PtrOf(gen.Bool())
	gens["OriginalVersion"] = gen.AlphaString()
	gens["PredicateExpression"] = gen.PtrOf(gen.AlphaString())
	gens["QueueDelayMs"] = gen.PtrOf(gen.Int())
	gens["RetentionDays"] = gen.PtrOf(gen.Int())
	gens["State"] = gen.PtrOf(gen.AlphaString())
	gens["StorageAccountSubscriptionId"] = gen.PtrOf(gen.AlphaString())
	gens["StorageEndpoint"] = gen.PtrOf(gen.AlphaString())
}

func Test_Servers_Databases_ExtendedAuditingSetting_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of Servers_Databases_ExtendedAuditingSetting_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForServers_Databases_ExtendedAuditingSetting_STATUS, Servers_Databases_ExtendedAuditingSetting_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForServers_Databases_ExtendedAuditingSetting_STATUS runs a test to see if a specific instance of Servers_Databases_ExtendedAuditingSetting_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForServers_Databases_ExtendedAuditingSetting_STATUS(subject Servers_Databases_ExtendedAuditingSetting_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual Servers_Databases_ExtendedAuditingSetting_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of Servers_Databases_ExtendedAuditingSetting_STATUS instances for property testing - lazily instantiated by
// Servers_Databases_ExtendedAuditingSetting_STATUSGenerator()
var servers_Databases_ExtendedAuditingSetting_STATUSGenerator gopter.Gen

// Servers_Databases_ExtendedAuditingSetting_STATUSGenerator returns a generator of Servers_Databases_ExtendedAuditingSetting_STATUS instances for property testing.
func Servers_Databases_ExtendedAuditingSetting_STATUSGenerator() gopter.Gen {
	if servers_Databases_ExtendedAuditingSetting_STATUSGenerator != nil {
		return servers_Databases_ExtendedAuditingSetting_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForServers_Databases_ExtendedAuditingSetting_STATUS(generators)
	servers_Databases_ExtendedAuditingSetting_STATUSGenerator = gen.Struct(reflect.TypeOf(Servers_Databases_ExtendedAuditingSetting_STATUS{}), generators)

	return servers_Databases_ExtendedAuditingSetting_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForServers_Databases_ExtendedAuditingSetting_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForServers_Databases_ExtendedAuditingSetting_STATUS(gens map[string]gopter.Gen) {
	gens["AuditActionsAndGroups"] = gen.SliceOf(gen.AlphaString())
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["IsAzureMonitorTargetEnabled"] = gen.PtrOf(gen.Bool())
	gens["IsManagedIdentityInUse"] = gen.PtrOf(gen.Bool())
	gens["IsStorageSecondaryKeyInUse"] = gen.PtrOf(gen.Bool())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["PredicateExpression"] = gen.PtrOf(gen.AlphaString())
	gens["QueueDelayMs"] = gen.PtrOf(gen.Int())
	gens["RetentionDays"] = gen.PtrOf(gen.Int())
	gens["State"] = gen.PtrOf(gen.AlphaString())
	gens["StorageAccountSubscriptionId"] = gen.PtrOf(gen.AlphaString())
	gens["StorageEndpoint"] = gen.PtrOf(gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
}
