// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package v1beta20211101storage

import (
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/conditions"
	"github.com/pkg/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// +kubebuilder:rbac:groups=sql.azure.com,resources=servers_databases_workloadgroups_workloadclassifiers,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=sql.azure.com,resources={servers_databases_workloadgroups_workloadclassifiers/status,servers_databases_workloadgroups_workloadclassifiers/finalizers},verbs=get;update;patch

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Severity",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].severity"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="Message",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].message"
// Storage version of v1beta20211101.Servers_Databases_WorkloadGroups_WorkloadClassifier
// Generator information:
// - Generated from: /sql/resource-manager/Microsoft.Sql/stable/2021-11-01/WorkloadClassifiers.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/workloadGroups/{workloadGroupName}/workloadClassifiers/{workloadClassifierName}
type Servers_Databases_WorkloadGroups_WorkloadClassifier struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              Servers_Databases_WorkloadGroups_WorkloadClassifier_Spec   `json:"spec,omitempty"`
	Status            Servers_Databases_WorkloadGroups_WorkloadClassifier_STATUS `json:"status,omitempty"`
}

var _ conditions.Conditioner = &Servers_Databases_WorkloadGroups_WorkloadClassifier{}

// GetConditions returns the conditions of the resource
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier) GetConditions() conditions.Conditions {
	return classifier.Status.Conditions
}

// SetConditions sets the conditions on the resource status
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier) SetConditions(conditions conditions.Conditions) {
	classifier.Status.Conditions = conditions
}

var _ genruntime.KubernetesResource = &Servers_Databases_WorkloadGroups_WorkloadClassifier{}

// AzureName returns the Azure name of the resource
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier) AzureName() string {
	return classifier.Spec.AzureName
}

// GetAPIVersion returns the ARM API version of the resource. This is always "2021-11-01"
func (classifier Servers_Databases_WorkloadGroups_WorkloadClassifier) GetAPIVersion() string {
	return string(APIVersion_Value)
}

// GetResourceScope returns the scope of the resource
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier) GetResourceScope() genruntime.ResourceScope {
	return genruntime.ResourceScopeResourceGroup
}

// GetSpec returns the specification of this resource
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier) GetSpec() genruntime.ConvertibleSpec {
	return &classifier.Spec
}

// GetStatus returns the status of this resource
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier) GetStatus() genruntime.ConvertibleStatus {
	return &classifier.Status
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Sql/servers/databases/workloadGroups/workloadClassifiers"
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier) GetType() string {
	return "Microsoft.Sql/servers/databases/workloadGroups/workloadClassifiers"
}

// NewEmptyStatus returns a new empty (blank) status
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier) NewEmptyStatus() genruntime.ConvertibleStatus {
	return &Servers_Databases_WorkloadGroups_WorkloadClassifier_STATUS{}
}

// Owner returns the ResourceReference of the owner, or nil if there is no owner
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier) Owner() *genruntime.ResourceReference {
	group, kind := genruntime.LookupOwnerGroupKind(classifier.Spec)
	return &genruntime.ResourceReference{
		Group: group,
		Kind:  kind,
		Name:  classifier.Spec.Owner.Name,
	}
}

// SetStatus sets the status of this resource
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier) SetStatus(status genruntime.ConvertibleStatus) error {
	// If we have exactly the right type of status, assign it
	if st, ok := status.(*Servers_Databases_WorkloadGroups_WorkloadClassifier_STATUS); ok {
		classifier.Status = *st
		return nil
	}

	// Convert status to required version
	var st Servers_Databases_WorkloadGroups_WorkloadClassifier_STATUS
	err := status.ConvertStatusTo(&st)
	if err != nil {
		return errors.Wrap(err, "failed to convert status")
	}

	classifier.Status = st
	return nil
}

// Hub marks that this Servers_Databases_WorkloadGroups_WorkloadClassifier is the hub type for conversion
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier) Hub() {}

// OriginalGVK returns a GroupValueKind for the original API version used to create the resource
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier) OriginalGVK() *schema.GroupVersionKind {
	return &schema.GroupVersionKind{
		Group:   GroupVersion.Group,
		Version: classifier.Spec.OriginalVersion,
		Kind:    "Servers_Databases_WorkloadGroups_WorkloadClassifier",
	}
}

// +kubebuilder:object:root=true
// Storage version of v1beta20211101.Servers_Databases_WorkloadGroups_WorkloadClassifier
// Generator information:
// - Generated from: /sql/resource-manager/Microsoft.Sql/stable/2021-11-01/WorkloadClassifiers.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/workloadGroups/{workloadGroupName}/workloadClassifiers/{workloadClassifierName}
type Servers_Databases_WorkloadGroups_WorkloadClassifierList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Servers_Databases_WorkloadGroups_WorkloadClassifier `json:"items"`
}

// Storage version of v1beta20211101.Servers_Databases_WorkloadGroups_WorkloadClassifier_Spec
type Servers_Databases_WorkloadGroups_WorkloadClassifier_Spec struct {
	// AzureName: The name of the resource in Azure. This is often the same as the name of the resource in Kubernetes but it
	// doesn't have to be.
	AzureName       string  `json:"azureName,omitempty"`
	Context         *string `json:"context,omitempty"`
	EndTime         *string `json:"endTime,omitempty"`
	Importance      *string `json:"importance,omitempty"`
	Label           *string `json:"label,omitempty"`
	MemberName      *string `json:"memberName,omitempty"`
	OriginalVersion string  `json:"originalVersion,omitempty"`

	// +kubebuilder:validation:Required
	// Owner: The owner of the resource. The owner controls where the resource goes when it is deployed. The owner also
	// controls the resources lifecycle. When the owner is deleted the resource will also be deleted. Owner is expected to be a
	// reference to a sql.azure.com/Servers_Databases_WorkloadGroup resource
	Owner       *genruntime.KnownResourceReference `group:"sql.azure.com" json:"owner,omitempty" kind:"Servers_Databases_WorkloadGroup"`
	PropertyBag genruntime.PropertyBag             `json:"$propertyBag,omitempty"`
	StartTime   *string                            `json:"startTime,omitempty"`
}

var _ genruntime.ConvertibleSpec = &Servers_Databases_WorkloadGroups_WorkloadClassifier_Spec{}

// ConvertSpecFrom populates our Servers_Databases_WorkloadGroups_WorkloadClassifier_Spec from the provided source
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier_Spec) ConvertSpecFrom(source genruntime.ConvertibleSpec) error {
	if source == classifier {
		return errors.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleSpec")
	}

	return source.ConvertSpecTo(classifier)
}

// ConvertSpecTo populates the provided destination from our Servers_Databases_WorkloadGroups_WorkloadClassifier_Spec
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier_Spec) ConvertSpecTo(destination genruntime.ConvertibleSpec) error {
	if destination == classifier {
		return errors.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleSpec")
	}

	return destination.ConvertSpecFrom(classifier)
}

// Storage version of v1beta20211101.Servers_Databases_WorkloadGroups_WorkloadClassifier_STATUS
type Servers_Databases_WorkloadGroups_WorkloadClassifier_STATUS struct {
	Conditions  []conditions.Condition `json:"conditions,omitempty"`
	Context     *string                `json:"context,omitempty"`
	EndTime     *string                `json:"endTime,omitempty"`
	Id          *string                `json:"id,omitempty"`
	Importance  *string                `json:"importance,omitempty"`
	Label       *string                `json:"label,omitempty"`
	MemberName  *string                `json:"memberName,omitempty"`
	Name        *string                `json:"name,omitempty"`
	PropertyBag genruntime.PropertyBag `json:"$propertyBag,omitempty"`
	StartTime   *string                `json:"startTime,omitempty"`
	Type        *string                `json:"type,omitempty"`
}

var _ genruntime.ConvertibleStatus = &Servers_Databases_WorkloadGroups_WorkloadClassifier_STATUS{}

// ConvertStatusFrom populates our Servers_Databases_WorkloadGroups_WorkloadClassifier_STATUS from the provided source
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier_STATUS) ConvertStatusFrom(source genruntime.ConvertibleStatus) error {
	if source == classifier {
		return errors.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleStatus")
	}

	return source.ConvertStatusTo(classifier)
}

// ConvertStatusTo populates the provided destination from our Servers_Databases_WorkloadGroups_WorkloadClassifier_STATUS
func (classifier *Servers_Databases_WorkloadGroups_WorkloadClassifier_STATUS) ConvertStatusTo(destination genruntime.ConvertibleStatus) error {
	if destination == classifier {
		return errors.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleStatus")
	}

	return destination.ConvertStatusFrom(classifier)
}

func init() {
	SchemeBuilder.Register(&Servers_Databases_WorkloadGroups_WorkloadClassifier{}, &Servers_Databases_WorkloadGroups_WorkloadClassifierList{})
}
