apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: azure-service-operator
    app.kubernetes.io/version: ${VERSION}
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
    - name: metrics
      port: 8443
  selector:
    app.kubernetes.io/name: azure-service-operator
