// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package storage

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_ProductPolicy_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 20
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of ProductPolicy via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForProductPolicy, ProductPolicyGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForProductPolicy runs a test to see if a specific instance of ProductPolicy round trips to JSON and back losslessly
func RunJSONSerializationTestForProductPolicy(subject ProductPolicy) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual ProductPolicy
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of ProductPolicy instances for property testing - lazily instantiated by ProductPolicyGenerator()
var productPolicyGenerator gopter.Gen

// ProductPolicyGenerator returns a generator of ProductPolicy instances for property testing.
func ProductPolicyGenerator() gopter.Gen {
	if productPolicyGenerator != nil {
		return productPolicyGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddRelatedPropertyGeneratorsForProductPolicy(generators)
	productPolicyGenerator = gen.Struct(reflect.TypeOf(ProductPolicy{}), generators)

	return productPolicyGenerator
}

// AddRelatedPropertyGeneratorsForProductPolicy is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForProductPolicy(gens map[string]gopter.Gen) {
	gens["Spec"] = Service_Products_Policy_SpecGenerator()
	gens["Status"] = Service_Products_Policy_STATUSGenerator()
}

func Test_ProductPolicyOperatorSpec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of ProductPolicyOperatorSpec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForProductPolicyOperatorSpec, ProductPolicyOperatorSpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForProductPolicyOperatorSpec runs a test to see if a specific instance of ProductPolicyOperatorSpec round trips to JSON and back losslessly
func RunJSONSerializationTestForProductPolicyOperatorSpec(subject ProductPolicyOperatorSpec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual ProductPolicyOperatorSpec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of ProductPolicyOperatorSpec instances for property testing - lazily instantiated by
// ProductPolicyOperatorSpecGenerator()
var productPolicyOperatorSpecGenerator gopter.Gen

// ProductPolicyOperatorSpecGenerator returns a generator of ProductPolicyOperatorSpec instances for property testing.
func ProductPolicyOperatorSpecGenerator() gopter.Gen {
	if productPolicyOperatorSpecGenerator != nil {
		return productPolicyOperatorSpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	productPolicyOperatorSpecGenerator = gen.Struct(reflect.TypeOf(ProductPolicyOperatorSpec{}), generators)

	return productPolicyOperatorSpecGenerator
}

func Test_Service_Products_Policy_STATUS_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of Service_Products_Policy_STATUS via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForService_Products_Policy_STATUS, Service_Products_Policy_STATUSGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForService_Products_Policy_STATUS runs a test to see if a specific instance of Service_Products_Policy_STATUS round trips to JSON and back losslessly
func RunJSONSerializationTestForService_Products_Policy_STATUS(subject Service_Products_Policy_STATUS) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual Service_Products_Policy_STATUS
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of Service_Products_Policy_STATUS instances for property testing - lazily instantiated by
// Service_Products_Policy_STATUSGenerator()
var service_Products_Policy_STATUSGenerator gopter.Gen

// Service_Products_Policy_STATUSGenerator returns a generator of Service_Products_Policy_STATUS instances for property testing.
func Service_Products_Policy_STATUSGenerator() gopter.Gen {
	if service_Products_Policy_STATUSGenerator != nil {
		return service_Products_Policy_STATUSGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForService_Products_Policy_STATUS(generators)
	service_Products_Policy_STATUSGenerator = gen.Struct(reflect.TypeOf(Service_Products_Policy_STATUS{}), generators)

	return service_Products_Policy_STATUSGenerator
}

// AddIndependentPropertyGeneratorsForService_Products_Policy_STATUS is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForService_Products_Policy_STATUS(gens map[string]gopter.Gen) {
	gens["Format"] = gen.PtrOf(gen.AlphaString())
	gens["Id"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.PtrOf(gen.AlphaString())
	gens["Type"] = gen.PtrOf(gen.AlphaString())
	gens["Value"] = gen.PtrOf(gen.AlphaString())
}

func Test_Service_Products_Policy_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of Service_Products_Policy_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForService_Products_Policy_Spec, Service_Products_Policy_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForService_Products_Policy_Spec runs a test to see if a specific instance of Service_Products_Policy_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForService_Products_Policy_Spec(subject Service_Products_Policy_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual Service_Products_Policy_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of Service_Products_Policy_Spec instances for property testing - lazily instantiated by
// Service_Products_Policy_SpecGenerator()
var service_Products_Policy_SpecGenerator gopter.Gen

// Service_Products_Policy_SpecGenerator returns a generator of Service_Products_Policy_Spec instances for property testing.
// We first initialize service_Products_Policy_SpecGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func Service_Products_Policy_SpecGenerator() gopter.Gen {
	if service_Products_Policy_SpecGenerator != nil {
		return service_Products_Policy_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForService_Products_Policy_Spec(generators)
	service_Products_Policy_SpecGenerator = gen.Struct(reflect.TypeOf(Service_Products_Policy_Spec{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForService_Products_Policy_Spec(generators)
	AddRelatedPropertyGeneratorsForService_Products_Policy_Spec(generators)
	service_Products_Policy_SpecGenerator = gen.Struct(reflect.TypeOf(Service_Products_Policy_Spec{}), generators)

	return service_Products_Policy_SpecGenerator
}

// AddIndependentPropertyGeneratorsForService_Products_Policy_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForService_Products_Policy_Spec(gens map[string]gopter.Gen) {
	gens["Format"] = gen.PtrOf(gen.AlphaString())
	gens["OriginalVersion"] = gen.AlphaString()
	gens["Value"] = gen.PtrOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForService_Products_Policy_Spec is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForService_Products_Policy_Spec(gens map[string]gopter.Gen) {
	gens["OperatorSpec"] = gen.PtrOf(ProductPolicyOperatorSpecGenerator())
}
